[template]
# Name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "kibana.yml.tmpl"

# The location to place the rendered configuration file
dest = "/opt/kibana/config/kibana.yml"

# The consul keys or directory to watch.  This is where the information to fill in the template will come from.
keys = [
    "/services/logging/es/host",
]

# File ownership and mode information
owner = "kibana"
mode = "0644"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
##check_cmd = "/usr/bin/supervisorctl kibana check"
##reload_cmd = "/usr/bin/supervisorctl kibana restart"